import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ProductsProvider from "@/providers/ProductsProvider";

import { Toaster } from "react-hot-toast";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Products - restaurante",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-dvh flex flex-col justify-start`}
      >
        <ProductsProvider>
          <Navbar />
          <Toaster position="top-center"  />
          {children}
        </ProductsProvider>
      </body>
    </html>
  );
}
